# Gabriel Graph

In [1]:
import numpy as np
from typing import List

In [2]:
expected_connections: np.ndarray = np.zeros((9, 9))
connected_points: List[List] = [
    [1, 0],
    [2, 1],
    [4, 3],
    [5, 4],
    [7, 6],
    [8, 7],
    [3, 0],
    [6, 3],
    [4, 1],
    [7, 4],
    [5, 2],
    [8, 5],
    [4, 0],
    [8, 4],
    [4, 2],
    [6, 4]
]

for point_a, point_b in connected_points:
    expected_connections[point_a, point_b] = 1

In [3]:
expected_connections

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 1., 0.]])

In [5]:
a = np.where(expected_connections == 1)

In [7]:
a

(array([1, 2, 3, 4, 4, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 8], dtype=int64),
 array([0, 1, 0, 0, 1, 2, 3, 2, 4, 3, 4, 4, 6, 4, 5, 7], dtype=int64))

In [8]:
list(zip(*a))



[(1, 0),
 (2, 1),
 (3, 0),
 (4, 0),
 (4, 1),
 (4, 2),
 (4, 3),
 (5, 2),
 (5, 4),
 (6, 3),
 (6, 4),
 (7, 4),
 (7, 6),
 (8, 4),
 (8, 5),
 (8, 7)]